### ISSUE TITLE
Duplicate buildings vs POIs inside a building

### ISSUE THREAD

**Issue by kachkaev** [zetx16/addr-duplicates#2]
👋 @zlant 

Thanks again for this useful tool!

I’ve spotted a few red lines for POIs inside a building. The lines show up because both the building and the POI use the same `addr:street` and `addr:housenumber` combination.

https://zlant.github.io/addr-duplicates/#17/53.18711/44.96755
<img width="910" alt="Screenshot 2021-06-12 at 23 56 46" src="https://user-images.githubusercontent.com/608862/121790714-fabd8c00-cbd9-11eb-881e-d54be813597f.png">

What could be cool is downloading the `building` tag and if it is not set at least for one of the duplicate points, render the line as semi-transparent or, say, yellow. This will help distinguish between the real duplicate buildings and the POIs inside buildings (which are not necessarily bad).

What do you think?

**Comment by zlant** [comment]
Implemented 👌

**Comment by kachkaev** [comment]
Nice! Thanks so much! Works like a charm 🚀

<img width="1018" alt="Screenshot 2021-06-13 at 09 54 28" src="https://user-images.githubusercontent.com/608862/121801077-63822400-cc2d-11eb-9bad-0442829c45f2.png">
